apiVersion: apps/v1
kind: Deployment
metadata:
  name: supervisor-app
  namespace: default
spec:
  selector:
    matchLabels:
      app: supervisor-app
  template:
    metadata:
      labels:
        app: supervisor-app
    spec:
      initContainers:
      - name: supervisor-init
        image: sharhanalhassan/custom-codeserver-local:superv0.0.2
        command: ['/bin/bash', '-c']
        args:
          - cp -R /home/coder/project/.vscode /mnt/data
        volumeMounts:
        - name: data-volume
          mountPath: /mnt/data

      containers:
      - name: supervisor-app
        image: sharhanalhassan/custom-codeserver-local:superv0.0.2
        command: ["/bin/bash", "-c"]
        args:
          - |
            sudo service docker start
            /usr/bin/code-server --auth none --host 0.0.0.0 --port 8080 .
        ports:
        - containerPort: 8080
        securityContext:
          privileged: true
        volumeMounts:
        - name: data-volume
          mountPath: /home/coder/project
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: supervisor-pvc
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: supervisor-app
  namespace: default
spec:
  ports:
    - port: 4545
      targetPort: 8080
  selector:
    app: supervisor-app
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: supervisor-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 
